haskell/hsc2hs

- Main.hs
- hsc2hs.cabal
As a last resort, try to find the `template-hsc.h` in `../lib` relative to the hsc2hs executable.
> Relative lookup of template-hsc.h

- ghc.mk
In 598303cbffcd230635fbce28ce4105d177fdf76a the Paths_hsc2hs module was added to the other-modules.
As such, it should be dropped from the ghc.mk
> Drop Paths_hsc2hs module from ghc.mk

- .travis.yml
- ATTParser.hs
- CrossCodegen.hs
- Flags.hs
- Main.hs
- Spec.hs
- hsc2hs.cabal
- test/asm/Makefile
- test/asm/aarch64-ios.s
- test/asm/aarch64.s
- test/asm/arm-ios.s
- test/asm/arm.s
- test/asm/tmp.c
- test/asm/x86-linux.s
- test/asm/x86_64-linux.s
- test/asm/x86_64-mac.s
- test/asm/x86_64-mingw32.s
Our current approach is taken from autoconf, and requires a binary search to
find constants.  This is not only very time consuming but also breaks when the
compiler fails to recognize an expression as constant.  As such we ask the
compiler to produce assembly, crudely parse that assembly and try to extract the
constant directly from the generated assembly.
> Adds a crude at&t assembly parser to resolve constants

- Main.hs
- changelog.md
See https://ghc.haskell.org/trac/ghc/ticket/13896
/cc @bgamari
> Add support to read command line arguments supplied via response files

- Spec.hs
- test/asm/Makefile
- test/asm/alpha-linux.s
- test/asm/hppa-linux.s
- test/asm/ia64-linux.s
- test/asm/m68k-linux.s
- test/asm/mips-linux.s
- test/asm/mips64-linux.s
- test/asm/nios2-linux.s
- test/asm/powerpc-linux.s
- test/asm/powerpc64-linux.s
- test/asm/powerpc64le-linux.s
- test/asm/s390-linux.s
- test/asm/s390x-linux.s
- test/asm/sh4-linux.s
- test/asm/sparc-linux.s
- test/asm/sparc64-linux.s
These are tests to illustrate GHC cross-compilation failures:
https://ghc.haskell.org/trac/ghc/ticket/14889
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>
> spec: add more assembly examples surrently broken for GHC

- HSCParser.hs
- changelog.md
Resolves https://github.com/haskell/hsc2hs/issues/12
> Accept a leading single quote for data constructor promotion

- HSCParser.hs
- hsc2hs.cabal
This fixes a warning, so that we can validate with `-Werror` again.
> Remove an unused match

- Common.hs
- changelog.md
- hsc2hs.cabal
This makes errors such as those in https://gitlab.haskell.org/ghc/ghc/issues/9775#note_203453 a lot rarer.
It does this by using two things:
1) It uses a process API that on Windows causes `waitForProcess` to wait for all child processes to complete.  This is required because the tools that `hsc2hs` use call `exec` which does not behave as you would expect on Windows.  The parent will return before the child finishes and so you have a race condition. On other OSes this flag has no effect.
2) It implements a retry queue which tries to delete a file 6 times if it's a permission error that prevented you from deleting it.  This because the temp file could be locked by an AV for scanning. The total wait time is ~3secs.
> hsc2hs: Make removeFile more reliable on Windows.

- UtilsCodegen.hs
- changelog.md
- template-hsc.h
hsc2hs is doing something shady, essentially it's generated headers etc are included *before* user headers. This changes the behavior of the includes.
On Windows it means we've always gotten deprecation warning but ignored it since `-Werror` dit not catch it before. However GCC9 is much better at this and so now we can't bootstrap GHC with GCC9 on Windows since this fails `-Werror`.
This patch changed it to put the template header first (certainly before first `_mingw.h` is included. We also define `__USE_MINGW_ANSI_STDIO` , this makes fixing of the other errors in GHC codebase possible.
> Fix order of inclusions

- Common.hs
- DirectCodegen.hs
- UtilsCodegen.hs
#23 introduced a couple of non-deterministic failures in hsc2hs on Windows.
1. `removeFile` should never be used in combination with `createProcess` on temporary files on Windows. Since tools such as AVs can have a lock on the file the removal may fail. Instead `finallyRemove` should always be used.
2. It created a race condition in `rawSystemL` by creating a dependency on an output file (the response file) and calling `createProcess` without using process jobs. Since it's invoking unix tools that use `spawn` it NEEDS to use process jobs to wait for when it's safe to delete the response file.
3. `openTempFile` is non-deterministic on Windows on anything but GHC 8.10. As such hsc2hs normally uses deterministic filenames for temporary files. By using `openTempFile` you get random failures …
> hsc2hs: fix non-deterministic failures for response file handlings

- Common.hs
- changelog.md
My fix in #29 assumed that response files were created in sequence. it turns out that the call to `withUtilsObject` also created one, but it was nested inside the call of another one creating a response file.
This would have been OK if the call in `withUtilsObject` gave the temp file function a different `basename` but it gave the same one.  This created a race condition in that two completely independent I/O write requests are issued almost simultaneously to the OS. If the OS handles them in the order they were given than it all works out. if the OS handles them out of order, or handles them in batch it would fail.
A simple fix would be to change the `base` in `withUtilsObject` but I felt this was a bit fragile. So instead I added a check to insure that we only write to non-existent …
> Fix nested temp calls with same base name

- Common.hs
- Compat/TempFile.hs
- UtilsCodegen.hs
- cbits/utils.c
- changelog.md
- hsc2hs.cabal
This PR inlines code from Base and makes the Temp file creation on Windows fully atomic and no longer just probabilistic atomic.
It also adds a pipe to `stderr` for any child process it creates. If the child process fails the `stderr` is displayed to the user regardless of the chosen verbosity.  This makes it easier to debug sensitive race conditions where using `-v` or `-keep-tmp-files` makes the condition go away.
The `stderr` also serve a second purpose in that it introduces a resource dependency between `hsc2hs` and any child process that inherits the handle.  This helps insure that on Windows control doesn't reach back to `hsc2hs` before resources of child processes have been flushed.
The latter has been an issue in `hsc2hs` for ages, a proper fix will be in `process` but this …
> Inline atomic actions for Windows and write more detailed diagnostics from hsc2hs

- Common.hs
- Compat/Process.hs
- cbits/utils.c
- changelog.md
- hsc2hs.cabal
Inline the fix process waiting code such that when older process libraries are used hsc2hs still behaves properly.
The problem is that during a GHC bootstrap the bootstrapping compiler will use a broken process and so hsc2hs won't be working correctly.
/CC @bgamari 
Continuation of https://github.com/haskell/hsc2hs/pull/39
> Inline process changes.

- Common.hs
This is the morally right thing to do and fixes FreeBSD,
which ships only with clang.
> Use cc rather than gcc as default compiler

- Compat/TempFile.hs
This is an extra check to hsc2hs to make sure that regardless of the base version you always not use the `tmp` directory workaround on Windows is the compiler is one that supports WINIO.
> winio: Make sure that with we don't use the TEMP workaround

- hsc2hs.cabal
Context: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4082#note_300462
> Bump base upper bound to 4.16

- src/ATTParser.hs
CLC has approved the proposal to add `{-# WARNING #-}` to `Data.List.{head,tail}` (https://github.com/haskell/core-libraries-committee/issues/87). It means that usage of `head` and `tail` will emit compile-time warnings.
This patch eliminates the only usage of `head` in `hsc2hs`.
> Avoid Data.List.{head,tail}

- src/CrossCodegen.hs
This is a fix for https://gitlab.haskell.org/ghc/ghc/-/issues/22981.
I've checked that GHC for wasm32-wasi builds successfully on AArch64 Linux with this patch.
> Fix pointer type detection in cross mode (again)

- src/Common.hs
- src/DirectCodegen.hs
See https://github.com/haskell/core-libraries-committee/issues/167
This is, of course, a bit speculative at the moment, but given that the change does not involve CPP, it should not hurt to merge it early to simplify further impact assessment.
> Future-proof against potential Prelude.foldl'

- hsc2hs.cabal
> Bump base bound to <4.20

- .github/workflows/haskell-ci.yml
- hsc2hs.cabal
Published as revision 2: https://hackage.haskell.org/package/hsc2hs-0.68.10/revisions/
> Allow base-4.20, bump CI to GHC 9.10

- .github/workflows/haskell-ci.yml
- hsc2hs.cabal
Superseds #94.
Published as revision 3 of 0.68.10.
> Bump Haskell-CI to GHC 9.12.0, bump base

- hsc2hs.cabal
> Bump base upper bound to <4.23
